[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
wall_contract = "2YVujTjqyFigZx4YYh1fFzWgPtd2bDwgUJNEjiDLVCcC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/jemwel/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
